name: CI
on: [push]

jobs:
  deploy_package_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Skyline DataMiner Deploy Action
        uses: SkylineCommunications/Skyline-DataMiner-Deploy-Action@v1.0.4
        with:
          api-key: ${{ secrets.ziinedevdeploykey }}
          # The path to the .sln file of the solution. Atm only DataMiner Automation Script solutions are supported. E.g ./Example/Script.sln. Required for stages: All and Upload.
          solution-path: ./AutomationScript.sln
          package-name: 'GetBookingsScript'
          version: '0.0.0-alpha'
